In [23]:
import pandas as pd

In [30]:
treino = pd.read_csv('../datasets/housing.csv')
treino = treino.drop('ocean_proximity', axis=1)
treino = treino.dropna() # Dropando valores nulos
treino.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0

In [25]:
treino.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [32]:
# Separando X e y
X = treino.drop('median_house_value',axis=1)
y = treino.median_house_value

# Usando modelo de regressão linear

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
# Criando algoritmo de regressão
reg = LinearRegression().fit(X, y)

In [35]:
# Modelo de teste
teste = pd.read_csv('../datasets/housing.csv')
teste = teste.drop('ocean_proximity', axis=1)
teste = teste.dropna() # Dropando valores nulos
teste.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value  
0       322.0       126.0         8.3252            452600.0  
1      2401.0      1138.0         8.3014            358500.0  
2       496.0       177.0         7.2574            352100.0

In [37]:
# Separando X e y
X_teste = teste.drop('median_house_value',axis=1)
y_teste = teste.median_house_value

In [ ]:
# Verificar modelo acerto 
reg.score(X_teste, y_teste)

0.6369116857335635

In [39]:
reg.intercept_

np.float64(-3585395.7478926242)

In [40]:
reg.coef_

array([-4.27301205e+04, -4.25097369e+04,  1.15790031e+03, -8.24972507e+00,
        1.13820707e+02, -3.83855780e+01,  4.77013513e+01,  4.02975217e+04])

## Persistência do modelo

In [41]:
# Fazendo dump do modelo
from joblib import dump
dump(reg, 'regressao.joblib')

['regressao.joblib']

# Usando o arquivo em outro arquivo

In [66]:
# Importando o qruivo de teste
import pandas as pd
teste = pd.read_csv('../datasets/housing.csv')

In [67]:
# Fazendo o load do modelo
from joblib import load
reg = load('regressao.joblib')

In [68]:
reg.intercept_

np.float64(-3585395.7478926242)

In [69]:
reg.coef_

array([-4.27301205e+04, -4.25097369e+04,  1.15790031e+03, -8.24972507e+00,
        1.13820707e+02, -3.83855780e+01,  4.77013513e+01,  4.02975217e+04])

In [70]:
# fazendo uma previsão

teste = teste.drop('ocean_proximity', axis=1)
teste = teste.dropna()
X_teste = teste.drop('median_house_value',axis=1)

reg.predict(X_teste)

array([411270.20746022, 415943.95527543, 380534.16332108, ...,
        24989.18869283,  37961.51486097,  55555.76850636])

In [ ]:
# Exportando o arquivo em excel, erro
previsao = reg.predict(X_teste)

X_teste['previsao'] = previsao

import openpyxl

X_teste.to_excel('previsoes_modelo.xlsx')

